"""create initial schema

Revision ID: 0872d1b95fae
Revises: 
Create Date: 2026-08-27 21:15:26.925639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0872d1b95fae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('occurred_start_date', sa.Date(), nullable=False),
    sa.Column('occurred_end_date', sa.Date(), nullable=True),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=20), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('causal_analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('dag_version', sa.String(length=20), nullable=False),
    sa.Column('baseline_window_start', sa.Date(), nullable=False),
    sa.Column('baseline_window_end', sa.Date(), nullable=False),
    sa.Column('comparison_window_start', sa.Date(), nullable=False),
    sa.Column('comparison_window_end', sa.Date(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('base_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('historical_on_time_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_of_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finished_good_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['finished_good_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finished_good_id', 'raw_material_id', name='uq_bom_pair')
    )
    op.create_table('causal_attributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('effect_event_id', sa.Integer(), nullable=False),
    sa.Column('candidate_node', sa.String(length=50), nullable=False),
    sa.Column('candidate_event_id', sa.Integer(), nullable=True),
    sa.Column('attribution_score', sa.Float(), nullable=False),
    sa.Column('attribution_rank', sa.Integer(), nullable=False),
    sa.Column('path_nodes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['causal_analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['candidate_event_id'], ['business_events.id'], ),
    sa.ForeignKeyConstraint(['effect_event_id'], ['business_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('opening_balance_qty', sa.Integer(), nullable=False),
    sa.Column('opening_balance_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', name='uq_inventory_item_product')
    )
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=False),
    sa.Column('planned_end', sa.Date(), nullable=False),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('planned_qty', sa.Integer(), nullable=False),
    sa.Column('actual_qty', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.Date(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('affected_order_count', sa.Integer(), nullable=True),
    sa.Column('impact_description', sa.Text(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['business_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('requested_delivery_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('ship_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('planned_quantity', sa.Integer(), nullable=False),
    sa.Column('planned_issue_date', sa.Date(), nullable=False),
    sa.Column('quantity_issued', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_fulfilled', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_shipped', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_receipt_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['purchase_order_lines.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('movement_type', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('goods_receipt_line_id', sa.Integer(), nullable=True),
    sa.Column('material_issue_id', sa.Integer(), nullable=True),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.Column('delivery_line_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(CASE WHEN goods_receipt_line_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN material_issue_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN production_order_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN delivery_line_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_stock_movement_exactly_one_source'),
    sa.ForeignKeyConstraint(['delivery_line_id'], ['delivery_lines.id'], ),
    sa.ForeignKeyConstraint(['goods_receipt_line_id'], ['goods_receipt_lines.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['material_issue_id'], ['material_issues.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_movements')
    op.drop_table('goods_receipt_lines')
    op.drop_table('delivery_lines')
    op.drop_table('sales_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_table('material_issues')
    op.drop_table('goods_receipts')
    op.drop_table('deliveries')
    op.drop_table('sales_orders')
    op.drop_table('risks')
    op.drop_table('purchase_orders')
    op.drop_table('production_orders')
    op.drop_table('inventory_items')
    op.drop_table('causal_attributions')
    op.drop_table('bill_of_materials')
    op.drop_table('suppliers')
    op.drop_table('products')
    op.drop_table('customers')
    op.drop_table('causal_analysis_runs')
    op.drop_table('business_events')
    # ### end Alembic commands ###
